cmake_minimum_required(VERSION 3.10)
project(bazele_programarii_master)

set(CMAKE_CXX_STANDARD 14)

# Lab 1 exercises
add_executable(bp2_lab1_ex16 "bp2-lab1/Bp 2-Lab-1-ex-16.cpp")

# Lab 2 exercises
add_executable(bp2_lab2_ex16 bp2-lab2/Bp2-Lab2-ex16.cpp)
add_executable(bp2_lab2_ex17 bp2-lab2/Bp2-Lab2-ex17.cpp)
add_executable(bp2_lab2_ex18 bp2-lab2/Bp2-Lab2-ex18.cpp)

# Lab 3 exercises
add_executable(bp2_lab3_ex7 bp2-lab3/Bp2-Lab3-ex7.cpp)
add_executable(bp2_lab3_ex10 bp2-lab3/Bp2-Lab3-ex10.cpp)
add_executable(bp2_lab3_ex14 bp2-lab3/Bp2-Lab3-ex14.cpp)

# Lab 4 exercises
add_executable(bp2_lab4_ex8 bp2-lab4/Bp2-Lab4-ex8.cpp)
add_executable(bp2_lab4_ex15 bp2-lab4/Bp2-Lab4-ex15.cpp)
add_executable(bp2_lab4_ex20 bp2-lab4/Bp2-Lab4-ex20.cpp)
